### ISSUE TITLE
net6-preview support.

### ISSUE THREAD

**Issue by ersintarhan** [qmfrederik/dotnet-packaging#192]
Hello, 
i tried deb packaging on net6-preview.
its throw exception : 

```
dotnet tool install --global dotnet-deb
Tool 'dotnet-deb' is already installed.
```
```

dotnet deb install
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Dotnet.Packaging.PackagingRunner.<>c__DisplayClass4_0.<Run>b__4()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Dotnet.Packaging.PackagingRunner.Run(String[] args) in /__w/1/s/dotnet-rpm/PackagingRunner.cs:line 184
   at Dotnet.Packaging.Program.Main(String[] args) in /__w/1/s/dotnet-deb/Program.cs:line 10
```

**Comment by qmfrederik** [comment]
Yes, we need to add `net6.0` as a build target and publish a new version to NuGet. #193 will hopefully do that.

**Comment by qmfrederik** [comment]
Version 0.1.217 of the dotnet-packaging tools support `net6.0`. Please give it a try!
